services:
  - type: web
    name: predicthealth-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python app/ml/train.py
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DATABASE_URL
      - key: FRONTEND_URL
    healthCheckPath: /health